<?php

/**
 * Autor: Reinan Rodrigues
 * Empresa: Vertex Solutions LTDA © 2026
 * Email: r.rodriguesjs@gmail.com
 */

namespace Modules\Teacher\Http\Controllers;

use App\Http\Controllers\Controller;

class TeacherController extends Controller
{
    public function index()
    {
        /** @var \App\Models\User $user */
        $user = auth()->user();

        // Count active classes for this teacher
        $activeClassesCount = $user->schoolClasses()->count();

        // Count lesson plans generated by this teacher
        $lessonPlansCount = $user->lessonPlans()->count();

        // Get the next class (simplified logic: next one today or tomorrow)
        $nextClass = $user->schoolClasses()
            ->whereHas('schedules', function ($q) {
                $q->where('day_of_week', now()->dayOfWeek)
                    ->where('start_time', '>', now()->format('H:i:s'));
            })
            ->with(['school', 'schedules' => function ($q) {
                $q->where('day_of_week', now()->dayOfWeek)
                    ->where('start_time', '>', now()->format('H:i:s'))
                    ->orderBy('start_time');
            }])
            ->first();

        // Recent notifications (Laravel database notifications for this user)
        $recentNotifications = $user->notifications()->latest()->take(5)->get();

        return view('teacher::dashboard', compact(
            'activeClassesCount',
            'lessonPlansCount',
            'nextClass',
            'recentNotifications'
        ));
    }

    public function stats()
    {
        return view('teacher::stats');
    }
}
